# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatApp-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatApp-MVVM



pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxGesture'
pod 'RxDataSources', '~> 3.0'
pod 'RxKeyboard'

  target 'chatApp-MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chatApp-MVVMUITests' do
    # Pods for testing
  end

end
